#!/xbin/bash

#
#  Samdroid v0.2.2 - backup script for Samsung Spica i5700 (Android 2.1)
#

if [ $(/xbin/mount | /xbin/grep /data | /xbin/wc -l) = 1 ]; then
        # Umount /data before we begin
        /xbin/umount /data
fi

if [ $(/xbin/mount | /xbin/grep /sdcard | /xbin/wc -l) = 0 ]; then
	/xbin/mount -t vfat /dev/block/mmcblk0p1 /sdcard
	if [ $(/xbin/mount | /xbin/grep /sdcard | /xbin/wc -l) = 0 ]; then
	echo "Can't mount /sdcard - exit!"
	exit 1
	fi
fi

case $1 in
        backup )
		echo "Create folder for backup [/sdcard/samdroid]..."
		/xbin/mkdir /sdcard/samdroid
		echo "Backuping..."
		/xbin/fdump -t /dev/bml6 /sdcard/samdroid/factoryfs.rfs
		/xbin/fdump -t /dev/bml5 /sdcard/samdroid/datafs.rfs
		cd /sdcard/samdroid
		echo "Create pda_Backup.tar for Odin..."
		TIMESTAMP="`date +%Y%m%d-%H%M`"
		/xbin/tar -cvvf pda_Backup_$TIMESTAMP.tar factoryfs.rfs datafs.rfs
		/xbin/rm /sdcard/samdroid/*.rfs
		cd /
                echo "Backup successful."
		exit 0;;
        restore )
                echo "Not supported yet (use Odin for restore)"
		exit 1;;
        * )
                echo "Usage: $0 backup|restore";;
esac
